

/*** Encontrar los valores distintos de unac columna **/
select distinct tipo_auxiliar 
from venta

select tipo_auxiliar from venta
group by tipo_auxiliar


/***** Si tengo duplicados en mi tabla *****/

CREATE TABLE MUSICA ( ID_MUSICA NUMBER , MUSICA VARCHAR2(50) ) ;

INSERT INTO MUSICA VALUES (1, 'PEARL JAM') ;
INSERT INTO MUSICA VALUES (1, 'PINK FLOYD') ;
INSERT INTO MUSICA VALUES(2,'RED HOT TO THE PEPPERS');
INSERT INTO MUSICA VALUES(3,'ARTIK MONKEYS');
INSERT INTO MUSICA VALUES(4,'STROKES');

INSERT INTO MUSICA VALUES (1, 'PEARL JAM') ;
SELECT * FROM MUSICA

SELECT DISTINCT ID_MUSICA FROM MUSICA


SELECT ID_MUSICA,COUNT(1) CANTIDAD
FROM MUSICA
GROUP BY ID_MUSICA
WHERE CANTIDAD >1 


SELECT ID_MUSICA,COUNT(1)
FROM MUSICA
WHERE ID_MUSICA !=4
GROUP BY ID_MUSICA
HAVING COUNT(1) >1

SELECT A.ROWID, A.* 
FROM MUSICA A

DELETE FROM  MUSICA
WHERE ROWID ='AAAFO5AABAAALSJAAD' ;

COMMIT;


SELECT * FROM MUSICA
/* DML SI COMMIT
INSERT 
UPDATE
DELETE
MERGE
(SELECT)

 */ 

/* DDL NO COMMIT 
CREATE TABLE
DROP TABLE
CREATE DATABASE
ALERT TABLE
TRUNCATE TABLE
*/ 
SELECT * FROM MUSICA

UPDATE MUSICA
SET  ID_MUSICA = 5
WHERE MUSICA = 'PINK FLOYD';
COMMIT;


DELETE FROM MUSICA
WHERE ROWID  = 'AAAFO5AABAAALSJAAD';
COMMIT;

 SELECT  M.ROWID ,M.*
FROM MUSICA M , (SELECT ID_MUSICA,COUNT(1)
                    FROM MUSICA
                    GROUP BY ID_MUSICA
                    HAVING COUNT(1) >1
                    ) D
                    WHERE M.ID_MUSICA = D.ID_MUSICA
 



DELETE FROM MUSICA 
WHERE  ID_MUSICA IN (
                  
                 SELECT  M.ROWID ,M.*
                    FROM MUSICA M , (SELECT ID_MUSICA,COUNT(1)
                    FROM MUSICA
                    GROUP BY ID_MUSICA
                    HAVING COUNT(1) >1
                    ) D
                    WHERE M.ID_MUSICA = D.ID_MUSICA
                
                    )
  
DECLARE

BEGIN
FOR VAR_CUR IN  ( SELECT  M.ROWID IDENTIFICATOR ,M.ID_MUSICA, MUSICA
                    FROM MUSICA M , (SELECT ID_MUSICA,COUNT(1)
                    FROM MUSICA
                    GROUP BY ID_MUSICA
                    HAVING COUNT(1) >1
                    ) D
                    WHERE M.ID_MUSICA = D.ID_MUSICA
                 )

          
          DELETE MUSICA
          WHERE ID_MUSICA = VAR_CUR.ID_MUSICA
          AND ROWID = VAR_IDENTIFICATOR
          

END;

SELECT  F_TEST(A.MUSICA) ID_MUSICA , MUSICA
FROM MUSICA A

SELECT F_TEST('STROKES') FROM DUAL


CREATE OR REPLACE FUNCTION F_TEST(P_MUSIC  VARCHAR2)  AS NUMBER
BEGIN
    V_ID NUMBER;
    SELECT ID_MUSIC 
    INTO V_ID
    FROM MUSICA
    WHERE MUSICA = P_MUSIC ;
    
    RETURN V_ID;
END; 


ALTER TABLE MUSICA ADD GENERO VARCHAR2(50);

UPDATE MUSICA
SET GENERO = CASE WHEN MUSICA!= 'PINK FLOYD' THEN 'ROCK ALTERNATIVO'
                ELSE 'ROCK' END;
            COMMIT;

SELECT * FROM MUSICA


CREATE TABLE PERSONA ( ID_PERSONA NUMBER, NOMBRE  VARCHAR2(100), APPATERNO VARCHAR2(100) ,  APMATERNO VARCHAR2(100))
INSERT INTO PERSONA VALUES (1, 'DAVID', 'MOLLERICONA', 'PEREZ');
INSERT INTO PERSONA VALUES (2, 'JORGE', 'QUIROGA', 'PEREZ');


CREATE TABLE PRSONA_MUSICA ( ID_PERSONA NUMBER, ID_MUSICA NUMBER,  IMPORTE NUMBER , CANTIDAD NUMBER );
 
INSERT INTO PRSONA_MUSICA VALUES (1,1, 100, 10 ) ;
INSERT INTO PRSONA_MUSICA VALUES (1,2, 70, 10 ) ;
INSERT INTO PRSONA_MUSICA VALUES (1,3, 20, 15 ) ;
INSERT INTO PRSONA_MUSICA VALUES (2,1, 200, 10 ) ;
INSERT INTO PRSONA_MUSICA VALUES (2,2, 280, 10 ) ;
INSERT INTO PRSONA_MUSICA VALUES (2,3, 200, 15 ) ;
INSERT INTO PRSONA_MUSICA VALUES (2,5, 100, 4 ) ;

COMMIT;

/** DETALLE */
SELECT * 
FROM  PRSONA_MUSICA PM , MUSICA M,PERSONA P
WHERE PM.ID_PERSONA = P.ID_PERSONA
AND PM.ID_MUSICA = M.ID_MUSICA

/***  REPORTE DE COMPRAS X GENERO POR NOMBRE */ 
SELECT M.GENERO,P.NOMBRE, P.APPATERNO,M.GENERO, SUM(IMPORTE) 
FROM  PRSONA_MUSICA PM , MUSICA M,PERSONA P
WHERE PM.ID_PERSONA = P.ID_PERSONA
AND PM.ID_MUSICA = M.ID_MUSICA
GROUP BY M.GENERO,P.NOMBRE, P.APPATERNO
ORDER BY 1 DESC

/***  REPORTE DE COMPRAS X PERSON MAX COMPRA*/

SELECT A.NOMBRE, A.APPATERNO,MAX (A.IMPORTESUM)
FROM (
    SELECT M.GENERO,P.NOMBRE, P.APPATERNO, SUM(IMPORTE) IMPORTESUM, MAX(IMPORTE)
    FROM  PRSONA_MUSICA PM , MUSICA M,PERSONA P
    WHERE PM.ID_PERSONA = P.ID_PERSONA
    AND PM.ID_MUSICA = M.ID_MUSICA
    GROUP BY M.GENERO,P.NOMBRE, P.APPATERNO
) A
GROUP BY A.NOMBRE, A.APPATERNO


SELECT *
FROM MUSICA 
WHERE GENERO LIKE 'ROCK%'
GROUP BY
HAVING

SELECT
FROM 
WHERE
GROUP BY
HAVING


DELETE  -- DML COMMIT;

DELETE FROM MUSICA; ROLLBACK; -- LENTO


TRUNCATE -- > RAPIDO DDL  SAVE GUARDA ESTRUCTURA , Y DROP TABLE (DATOS PIERDEN) 

MAX
MIN
SUM
AVG
COUNT
UNIQUE =DISTINCT 
SELECT DISTINCT ID_PRESENTACION FROM VENTA

ALTER TABLE
