/* LOG DE PROCESOS*/ 

CREATE TABLE  LOG_DE_PROCESOS
    (NOMBRE_PROCESO VARCHAR2(50),
     FEC_INICIO DATE,
     FEC_FIN DATE,
     COMENTARIO VARCHAR2 (500),
     CANT_REG NUMBER,
     CORRECTO VARCHAR2(1)
     )
     
