/********************CREAR ESTRUCTURAS EN EL STAGE *****/

CREATE TABLE STG_CIUDADES
NOLOGGING
AS
SELECT * FROM distribuidor.CIUDADES
where rownum<1 ;

CREATE TABLE STG_DEPARTAMENTO
NOLOGGING
AS
SELECT * FROM distribuidor.departamentos
where rownum<1  ;


CREATE TABLE STG_PRODUCTOS
NOLOGGING
AS
SELECT * FROM distribuidor.productos
where rownum<1 ;

CREATE TABLE STG_PRESENTACIONES
NOLOGGING
AS
SELECT * FROM distribuidor.PRESENTACIONES
where rownum<1 ;


CREATE TABLE STG_RUBROS
NOLOGGING
AS
SELECT * FROM distribuidor.rubros
where rownum<1 ;


CREATE TABLE STG_SUBRUBROS
NOLOGGING
AS
SELECT * FROM distribuidor.subrubros 
where rownum<1 ;


CREATE TABLE STG_CLIENTES_RUBROS
NOLOGGING
AS
SELECT * FROM distribuidor.clientes_rubros
where rownum<1 ;


/******************* copias de las dimensiones y facts del star ********/

/******* si no tengo accesos a las tablas  grant ****/

CREATE TABLE STG_DIM_GEOGRAFIA
NOLOGGING
AS
SELECT * FROM star.dim_geografia
where rownum<1 ;

CREATE TABLE stg_dim_productos
NOLOGGING
AS
SELECT * FROM star.dim_productos
where rownum<1 ;


CREATE TABLE stg_dim_clientes
NOLOGGING
AS
SELECT * FROM star.dim_clientes
where rownum<1 ;

/********** CREAR ESTRUCTURA DE STG VENTA ****/


drop table STG_VENTAS_COPIA;

CREATE TABLE STG_VENTAS_COPIA
NOLOGGING
AS
SELECT * FROM distribuidor.venta


CREATE TABLE STG_FACT_VENTA
NOLOGGING
AS
SELECT * FROM star.fact_venta
where rownum<1 ;



/*********** CREAR ESTRUCTURA STG_DIM_TIEMPO ***/

CREATE TABLE STG_DIM_TIEMPO
AS
SELECT * FROM STAR.DIM_TIEMPO
WHERE ROWNUM <1

/*********** CREAR UNA SEQUENCIA  ************/

CREATE SEQUENCE SEQ_IDW_GEO  START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_IDW_CLI START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_IDW_PROD START WITH 1 INCREMENT BY 1 ;


/**** CREAMOS LA TABLA DE LOG DE PROCESOS ****/

CREATE TABLE  LOG_DE_PROCESOS
    (NOMBRE_PROCESO VARCHAR2(50),
     FEC_INICIO DATE,
     FEC_FIN DATE,
     COMENTARIO VARCHAR2 (500),
     CANT_REG NUMBER,
     CORRECTO VARCHAR2(1)
     )
  /*********** CREAMOS EL PROCESO DE LOG DE PROCESOS*/ 
     
  CREATE OR REPLACE PROCEDURE P_INSERTAR_INFO_PROC
(
V_NOMBRE_PROCESO LOG_DE_PROCESOS.NOMBRE_PROCESO%TYPE,
V_FEC_INICIO  LOG_DE_PROCESOS.FEC_INICIO%TYPE,
V_FEC_FIN     LOG_DE_PROCESOS.FEC_FIN%TYPE,
V_COMENTARIO  LOG_DE_PROCESOS.COMENTARIO%TYPE,
V_CANT_REG    LOG_DE_PROCESOS.CANT_REG%TYPE,
V_CORRECTO    LOG_DE_PROCESOS.CORRECTO%TYPE
)
AS
BEGIN
    INSERT INTO LOG_DE_PROCESOS VALUES
    (V_NOMBRE_PROCESO,
     V_FEC_INICIO,
     V_FEC_FIN,
     V_COMENTARIO,
     V_CANT_REG,
     V_CORRECTO)
    ;
    COMMIT
    ;
END
;
