
/******  PARA OBTENER EL SCRIPT DE TABLAS DE GRANTS *******/
SELECT 'GRANT SELECT ON '||TABLE_NAME || ' TO STAGE;'  FROM USER_TABLES


GRANT SELECT ON CIUDADES TO STAGE;
GRANT SELECT ON CLIENTES_RUBROS TO STAGE;
GRANT SELECT ON DEPARTAMENTOS TO STAGE;
GRANT SELECT ON PRESENTACIONES TO STAGE;
GRANT SELECT ON PRODUCTOS TO STAGE;
GRANT SELECT ON RUBROS TO STAGE;
GRANT SELECT ON STOCK TO STAGE;
GRANT SELECT ON SUBRUBROS TO STAGE;
GRANT SELECT ON VENTA TO STAGE;