--
--ER/Studio 6.6 SQL Code Generation
-- Project :      ER_ORDERS_oracle10g.dm1
--
-- Date Created : Sunday, March 02, 2008 18:10:44
-- Target DBMS : Oracle 9i
--

-- 
-- TABLE: CATEGORIES 
--

CREATE TABLE CATEGORIES(
    CATEGORYID      NUMBER(38, 0)    NOT NULL,
    CATEGORYNAME    VARCHAR2(15)     NOT NULL,
    DESCRIPTION     VARCHAR2(50),
    CONSTRAINT PK_CATEGORIES PRIMARY KEY (CATEGORYID)
)
;



-- 
-- TABLE: CUSTOMERS 
--

CREATE TABLE CUSTOMERS(
    CUSTOMERID      VARCHAR2(5)     NOT NULL,
    COMPANYNAME     VARCHAR2(40)    NOT NULL,
    CONTACTNAME     VARCHAR2(30),
    CONTACTTITLE    VARCHAR2(30),
    ADDRESS         VARCHAR2(60),
    CITY            VARCHAR2(15),
    REGION          VARCHAR2(15),
    POSTALCODE      VARCHAR2(10),
    COUNTRY         VARCHAR2(15),
    PHONE           VARCHAR2(24),
    FAX             VARCHAR2(24),
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMERID)
)
;



-- 
-- TABLE: EMPLOYEES 
--

CREATE TABLE EMPLOYEES(
    EMPLOYEEID         NUMBER(38, 0)    NOT NULL,
    LASTNAME           VARCHAR2(20)     NOT NULL,
    FIRSTNAME          VARCHAR2(10)     NOT NULL,
    TITLE              VARCHAR2(30),
    TITLEOFCOURTESY    VARCHAR2(25),
    BIRTHDATE          DATE,
    HIREDATE           DATE,
    ADDRESS            VARCHAR2(60),
    CITY               VARCHAR2(15),
    REGION             VARCHAR2(15),
    POSTALCODE         VARCHAR2(10),
    COUNTRY            VARCHAR2(15),
    HOMEPHONE          VARCHAR2(24),
    EXTENSION          VARCHAR2(4),
    NOTES              LONG,
    REPORTSTO          NUMBER(38, 0),
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEEID)
)
;



-- 
-- TABLE: ORDERDETAILS 
--

CREATE TABLE ORDERDETAILS(
    ORDERID      NUMBER(38, 0)    NOT NULL,
    PRODUCTID    NUMBER(38, 0)    NOT NULL,
    UNITPRICE    NUMBER(19, 2)    DEFAULT 0 NOT NULL,
    QUANTITY     NUMBER(5, 0)     DEFAULT 1 NOT NULL,
    DISCOUNT     NUMBER(5, 2)     DEFAULT 0 NOT NULL,
    CONSTRAINT PKORDERDETAILS PRIMARY KEY (ORDERID, PRODUCTID)
)
;



-- 
-- TABLE: ORDERS 
--

CREATE TABLE ORDERS(
    ORDERID           NUMBER(38, 0)    NOT NULL,
    CUSTOMERID        VARCHAR2(5),
    EMPLOYEEID        NUMBER(38, 0),
    ORDERDATE         DATE,
    REQUIREDDATE      DATE,
    SHIPPEDDATE       DATE,
    SHIPVIA           NUMBER(38, 0),
    FREIGHT           NUMBER(19, 2)    DEFAULT 0,
    SHIPNAME          VARCHAR2(40),
    SHIPADDRESS       VARCHAR2(60),
    SHIPCITY          VARCHAR2(15),
    SHIPREGION        VARCHAR2(15),
    SHIPPOSTALCODE    VARCHAR2(10),
    SHIPCOUNTRY       VARCHAR2(15),
    CONSTRAINT ORDERS PRIMARY KEY (ORDERID)
)
;



-- 
-- TABLE: PRODUCTS 
--

CREATE TABLE PRODUCTS(
    PRODUCTID          NUMBER(38, 0)    NOT NULL,
    PRODUCTNAME        VARCHAR2(40)     NOT NULL,
    SUPPLIERID         NUMBER(38, 0),
    CATEGORYID         NUMBER(38, 0),
    QUANTITYPERUNIT    VARCHAR2(20),
    UNITPRICE          NUMBER(19, 2)    DEFAULT 0,
    UNITSINSTOCK       NUMBER(5, 0)     DEFAULT 0,
    UNITSONORDER       NUMBER(5, 0)     DEFAULT 0,
    REORDERLEVEL       NUMBER(5, 0)     DEFAULT 0,
    DISCONTINUED       NUMBER(1, 0),
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCTID)
)
;



-- 
-- TABLE: SHIPPERS 
--

CREATE TABLE SHIPPERS(
    SHIPPERID      NUMBER(38, 0)    NOT NULL,
    COMPANYNAME    VARCHAR2(40)     NOT NULL,
    PHONE          VARCHAR2(24),
    CONSTRAINT PKPRODUCTS PRIMARY KEY (SHIPPERID)
)
;



-- 
-- TABLE: SUPPLIERS 
--

CREATE TABLE SUPPLIERS(
    SUPPLIERID      NUMBER(38, 0)    NOT NULL,
    COMPANYNAME     VARCHAR2(40)     NOT NULL,
    CONTACTNAME     VARCHAR2(30),
    CONTACTTITLE    VARCHAR2(30),
    ADDRESS         VARCHAR2(60),
    CITY            VARCHAR2(15),
    REGION          VARCHAR2(15),
    POSTALCODE      VARCHAR2(10),
    COUNTRY         VARCHAR2(15),
    PHONE           VARCHAR2(24),
    FAX             VARCHAR2(24),
    CONSTRAINT PKSUPPLIERS PRIMARY KEY (SUPPLIERID)
)
;



-- 
-- TABLE: ORDERDETAILS 
--

ALTER TABLE ORDERDETAILS ADD 
    FOREIGN KEY (ORDERID)
    REFERENCES ORDERS(ORDERID) ON DELETE CASCADE
;

ALTER TABLE ORDERDETAILS ADD 
    FOREIGN KEY (PRODUCTID)
    REFERENCES PRODUCTS(PRODUCTID)
;


-- 
-- TABLE: ORDERS 
--

ALTER TABLE ORDERS ADD 
    FOREIGN KEY (CUSTOMERID)
    REFERENCES CUSTOMERS(CUSTOMERID)
;

ALTER TABLE ORDERS ADD 
    FOREIGN KEY (EMPLOYEEID)
    REFERENCES EMPLOYEES(EMPLOYEEID)
;

ALTER TABLE ORDERS ADD 
    FOREIGN KEY (SHIPVIA)
    REFERENCES SHIPPERS(SHIPPERID)
;


-- 
-- TABLE: PRODUCTS 
--

ALTER TABLE PRODUCTS ADD 
    FOREIGN KEY (CATEGORYID)
    REFERENCES CATEGORIES(CATEGORYID)
;

ALTER TABLE PRODUCTS ADD 
    FOREIGN KEY (SUPPLIERID)
    REFERENCES SUPPLIERS(SUPPLIERID)
;


