
/*  TABLAS EXISTENTES EN EL ESQUEMA INSCRIPICION*/
SELECT * FROM USER_TABLES 

/* CONSULTAS DE TABLAS */
SELECT * FROM PELICULAS

/*GUARDAR LOS REGISTROS*/
commit;

/* INSERT UN REGISTRO EN UN TABLA */
INSERT INTO PELICULAS VALUES(4, 'MULAN','ACCION');
COMMIT;

/* INSERT UN REGISTRO EN UN TABLA Y DESHACER EL REGISTRO */
INSERT INTO PELICULAS VALUES(5, 'INTERESTELAR','CIENCIAFICCION');
ROLLBACK;

/*ELIMINAR LA TABLA */ 
DROP TABLE MATERIA  

/*CREAR LA TABLA */ 
CREATE TABLE MATERIA( ID_MATERIA NUMBER , MATERIA VARCHAR(150)) ;

SELECT * FROM MATERIA
/*REALIZAR REGISTROS EN LAS TABLAS */
INSERT INTO MATERIA VALUES (1, 'Introducción a Ciencia de Datos');
INSERT INTO MATERIA VALUES (2, 'Analisis Estadistico');
INSERT INTO MATERIA VALUES (3, 'Almacenes de Datos');
INSERT INTO MATERIA VALUES (1,'Deep Learning');

COMMIT;

/* MODIFICAR LOS REGISTROS DE UNA TABLA */
UPDATE MATERIA
SET MATERIA = 'Analisis Estadístico'
WHERE  ID_MATERIA =2;
COMMIT;

/* ELIMINAR UN REGISTRO O VARIOS, O TODO DE LA TABLA, PERO SI BORRO TODO NO ES EFICIENTE, PREFERIBLE UTILIZAR TRUNCATE*/
DELETE MATERIA WHERE MATERIA ='Deep Learning';
COMMIT;

/* PUEDO RECUPERAR LOS REGISTROS HACIENDO ROLLBACK CON DELETE (SIN QUE ANTES EXISTA UN COMMIT) */
DELETE FROM MATERIA ; 
ROLLBACK

/* LIMPIAR LOS DATOS , PERO NO PUEDO HACER ROLLBACK  */ 
TRUNCATE TABLE MATERIA
ROLLBACK

SELECT * FROM MATERIA 

 /* DML - DATA MANIPULATION LANGUAGE (NECESITAN COMMIT)*/ 
 INSERT
 UPDATE
 DELETE
 MERGE --UPSSERT
 *SELECT 
 
 /* DDL - DATA DEFINITION LANGUAGE  (NO NECESITAN COMMIT )*/
 TRUNCATE TABLE ( SAVE CREATE TABLE, DROP TABLE , CREATE TABLE) -- DELETE * FROM MATERIA
 CREATE TABLE
 ALTER TABLE 
 DROP TABLE
 CREATE TRIGGER


ALTER TABLE MATERIA MODIFY MATERIA VARCHAR2(200)

 
