-- (INNER) JOIN


SELECT G.ID_GRUPO, G.GRUPO FROM GRUPO G

SELECT  * FROM ALUMNO

-- Que alumnos estan en que grup


SELECT * 
FROM GRUPO G, ALUMNO A
WHERE G.ID_GRUPO = A.ID_GRUPO
--AND G.ID_GRUPO = 6
ORDER BY GRUPO DESC

/* ANSY SQL */ 
SELECT * 
FROM GRUPO G JOIN ALUMNO A
ON G.ID_GRUPO = A.ID_GRUPO
WHERE G.ID_GRUPO =6
ORDER BY GRUPO DESC

SELECT * 
FROM GRUPO G INNER JOIN ALUMNO A
ON G.ID_GRUPO = A.ID_GRUPO
ORDER BY GRUPO DESC

SELECT * 
FROM GRUPO G INNER JOIN ALUMNO A
ON G.ID_GRUPO = A.ID_GRUPO
WHERE G.ID_GRUPO = 6
ORDER BY GRUPO DESC



-- LEFT JOIN

SELECT * FROM GRUPO
SELECT * FROM ALUMNO
WHERE ID_GRUPO =9 

SELECT * FROM LOCALIDAD
INSERT INTO GRUPO VALUES(9 , 'WILLSTERMAN');
COMMIT;

alter table ALUMNO  drop constraint fk_grupo_alumno;

INSERT INTO ALUMNO (ID_ALUMNO, CI, NOMBRE_COMPLETO, NOMBRE, APELLIDOPAT, APELLIDOMAT, ID_GRUPO, CORREO, TRABAJO, ID_LOCALIDAD) 
                    VALUES ('26','5153905', 'FERNANDO TERRAZAS ALVAREZ' ,'','','',11, 'fernando.terrazas.a@gmail.com','IPPB SRL',6);
COMMIT;
                    
SELECT *
FROM GRUPO G FULL OUTER JOIN ALUMNO A
ON G.ID_GRUPO = A.ID_GRUPO 



SELECT *
FROM GRUPO G, ALUMNO A
WHERE G.ID_GRUPO  = A.ID_GRUPO (+)


/* ANSY SQL */ 
SELECT * 
FROM GRUPO G LEFT OUTER JOIN ALUMNO A
ON G.ID_GRUPO = A.ID_GRUPO
ORDER BY GRUPO DESC

SELECT *
FROM GRUPO G, ALUMNO A
WHERE G.ID_GRUPO = A.ID_GRUPO(+)
ORDER BY GRUPO DESC


-- RIGHT JOIN
SELECT * 
FROM  ALUMNO A RIGHT JOIN GRUPO G 
ON G.ID_GRUPO = A.ID_GRUPO
ORDER BY GRUPO DESC

SELECT * 
FROM  ALUMNO A , GRUPO G 
WHERE G.ID_GRUPO(+)  = A.ID_GRUPO
ORDER BY GRUPO DESC


-- FULL OUTER JOIN
SELECT * 
FROM  ALUMNO A FULL OUTER JOIN GRUPO G 
ON G.ID_GRUPO = A.ID_GRUPO
ORDER BY GRUPO DESC

/********** GROUP BY   ******/

SELECT A.*, AM.*
FROM ALUMNOMATERIA AM,ALUMNO A 
WHERE A.ID_ALUMNO = 1
AND AM.ID_ALUMNO = A.ID_ALUMNO


SELECT NOMBRE_COMPLETO, MONTO
FROM ALUMNOMATERIA AM,ALUMNO A 
WHERE A.ID_ALUMNO = 1
AND AM.ID_ALUMNO = A.ID_ALUMNO


SELECT NOMBRE_COMPLETO, SUM(MONTO), MAX(MONTO) , MIN(MONTO) , AVG(MONTO)
FROM ALUMNOMATERIA AM,ALUMNO A 
WHERE A.ID_ALUMNO = 1
AND AM.ID_ALUMNO = A.ID_ALUMNO
GROUP BY NOMBRE_COMPLETO

SELECT CI,CORREO,NOMBRE_COMPLETO, SUM(MONTO)
FROM ALUMNOMATERIA AM,ALUMNO A 
--WHERE A.ID_ALUMNO = 1
WHERE AM.ID_ALUMNO = A.ID_ALUMNO
GROUP BY CI,CORREO,NOMBRE_COMPLETO


SELECT CI,CORREO,NOMBRE_COMPLETO, SUM(MONTO)
FROM ALUMNOMATERIA AM,ALUMNO A 
--WHERE MONTO <= 800
WHERE AM.ID_ALUMNO = A.ID_ALUMNO
GROUP BY CI,CORREO,NOMBRE_COMPLETO
HAVING SUM(MONTO) <=800


SELECT *
FROM (
        SELECT CI,CORREO,NOMBRE_COMPLETO, MONTO
        from ALUMNOMATERIA AM,ALUMNO A 
        WHERE AM.ID_ALUMNO = A.ID_ALUMNO
     )  
/* subconsultas a nivel de joing */
-- NRO TABLES = 3
-- NRO JOINS = NRO_TABLES -1 = 3-1 =2
SELECT CI,CORREO,NOMBRE_COMPLETO,GRUPO, MONTO
from ALUMNOMATERIA AM,ALUMNO A ,GRUPO G
WHERE AM.ID_ALUMNO = A.ID_ALUMNO
AND A.ID_GRUPO =G.ID_GRUPO

/* subconsultas a nivel de select (function) */ 
SELECT CI,CORREO,NOMBRE_COMPLETO,(SELECT GRUPO FROM GRUPO G WHERE G.ID_GRUPO = A.ID_GRUPO ) GRUPO , MONTO
from ALUMNOMATERIA AM,ALUMNO A 
WHERE AM.ID_ALUMNO = A.ID_ALUMNO

/* subconsultas a nivel de where */ 

SELECT A.ID_ALUMNO, CI,CORREO,NOMBRE_COMPLETO,(SELECT GRUPO FROM GRUPO G WHERE G.ID_GRUPO = A.ID_GRUPO ) GRUPO , MONTO
from ALUMNOMATERIA AM,ALUMNO A 
WHERE AM.ID_ALUMNO = A.ID_ALUMNO
AND A.ID_ALUMNO IN  (SELECT  ID_ALUMNO FROM ALUMNOMATERIA WHERE MONTO <=800)



SELECT * FROM ALUMNOMATERIA  A 
 WHERE ID_ALUMNO =1
